# services:
#   - type: web
#     name: social-automation
#     env: python
#     plan: free
#     buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
#     startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
#     envVars:
#       - key: PYTHON_VERSION
#         value: 3.11.9

services:
  - type: web
    name: social-automation
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: "uvicorn mainY:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGODB_URI
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_OAUTH_REDIRECT_URI
        sync: false